export const ROLES = {
  CITIZEN: "CITIZEN",
  EMPLOYEE: "EMPLOYEE",
  DEPARTMENT_HEAD:
    "DEPARTMENT_HEAD",
  ADMIN: "ADMIN",
};

export const STATUS = {
  PENDING: "PENDING",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  RESOLVED: "RESOLVED",
  CLOSED: "CLOSED",
};

export const PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};